export const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';

export const API_ENDPOINTS = {
  auth: {
    register: '/api/users/register',
    login: '/api/users/login',
    sendVerificationCode: '/api/users/send-verification-code',
    verifyCode: '/api/users/verify-code',
  },
  users: {
    me: '/api/users/me',
    byId: (id: number) => `/api/users/${id}`,
    byUsername: (username: string) => `/api/users/search/username/${username}`,
  },
  teams: {
    list: '/api/teams',
    byId: (id: number) => `/api/teams/${id}`,
    create: '/api/teams',
    update: (id: number) => `/api/teams/${id}`,
    delete: (id: number) => `/api/teams/${id}`,
    members: (id: number) => `/api/teams/${id}/members`,
    addMember: '/api/teams/members',
    removeMember: (id: number) => `/api/teams/members/${id}`,
    offerMembers: '/api/teams/offer-members',
  },
  tournaments: {
    list: '/api/tournaments',
    byId: (id: number) => `/api/tournaments/${id}`,
    create: '/api/tournaments',
    update: (id: number) => `/api/tournaments/${id}`,
    delete: (id: number) => `/api/tournaments/${id}`,
    participants: (id: number) => `/api/tournaments/${id}/participants`,
    addParticipant: '/api/tournaments/participants',
    removeParticipant: (id: number) => `/api/tournaments/participants/${id}`,
    report: (id: number) => `/api/tournaments/${id}/report`,
  },
  games: {
    list: '/api/games',
    byId: (id: number) => `/api/games/${id}`,
    create: '/api/games',
    update: (id: number) => `/api/games/${id}`,
    delete: (id: number) => `/api/games/${id}`,
    participants: (id: number) => `/api/games/${id}/participants`,
    addParticipant: '/api/games/participants',
    removeParticipant: (id: number) => `/api/games/participants/${id}`,
    updateParticipant: (id: number) => `/api/games/participants/${id}`,
    addLocation: '/api/games/locations',
    linkLocation: '/api/games/link-location',
    addReferee: '/api/games/referees',
    linkReferee: '/api/games/link-referee',
    referees: (id: number) => `/api/games/${id}/referees`,
    allReferees: '/api/games/all-referees',
    allLocations: '/api/games/all-locations',
    allSponsors: '/api/games/sponsors',
    createSponsor: '/api/games/sponsors',
    addMatchSponsor: '/api/games/match-sponsors',
    sponsors: (id: number) => `/api/games/${id}/sponsors`,
    findSimilar: '/api/games/find-similar-games',
  },
};
